#!/bin/bash
#SBATCH -p debug -t 23:00:00
#SBATCH -N 1 --tasks-per-node=8
#SBATCH -J hymls_rev_test

cd ${HOME}/testing/fredwubs/hymls/testSuite/rev_tests

echo 'Testing '
pwd
git log --format="%H" -n 1
git reset --hard
python test_rev.py `git log --format="%H" -n 1`

python mail_results.py `git log --format="%H" -n 1`
